# IBC Configuration File

# Gateway Mode
TradingMode=paper
IbDir=~/Applications/IBJts
IBCINI=~/Projects/ibkr_bot/scripts/ibc/config.ini
IBCPath=~/Projects/ibkr_bot/scripts/ibc

# Login credentials (replace with yours or use environment variables)
# It's better to export TWS_USERID and TWS_PASSWORD in the terminal before running
IbLoginId=
IbPassword=

# Keep Gateway running
FixTradingMode=yes
OverrideTwsApiPort=4002
AcceptIncomingConnectionAction=accept
AcceptIncomingConnectionRejectReason=

# Logging
LogToConsole=yes
